language: go

go:
  - 1.13.x

sudo: false

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - env
  - golangci-lint run
  - go test -v -race ./...

before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: M5B06y/LnhXnd3zu4WZnI1PB5bk+psPgUXB8j8diNH23gW9baRYqzmFm9lkdrgIBR9c9l6WlPia6fOK6w0MS0ok4c6r9OG8pHK7KrYFpwnSTYA99dfIS7Vg+G2/21RQduQkUC2XTemWvyjmzvC2Xk3FkFwV6PLjk0+P7ym2FO/g8V/NsRKOEBzQ7twg1taWQBVlT+ZmBizuoaUKdCyFVh4ksCDYebXTjh1Lp2ZQO+4inBKDX2BNxuIbp82LXpZE5C70tyyHiPULKamUSwuDHQqAAOZQ8ZgOFZSlrlfgDXn8Ix4QgFsfvSVT6eMH/q4iWfib9JnYqhoGTrYg0ntv7ZdpbOgW8HpZVw4vdn1u/si99f2t2zJXzL365F5ObXegg0htG6Q2nqHBa89G0GpLkIt+9OVlf6tipL02JKpg9do8/bUdhLv1KY+1qe76qNiI3UlFinOkYg8IoxrrQsVdIWsCCxCXr4ayhgN0PfFOdRXTSlCMzxqMfHCxIYHkDLHpSkFYnhsoWG3XOTmymwZA/IGAlJCcNmSiIVf1Uja6ow5nf7HTV5rHp54TmrAej4j9vSoQ9zj2hH4vp5p2oLLHynV0Itop2PAN528GNATJGHilxTAQGE1yv4dmG9Ap/YjwCc2TomAyUE+hO/L+jnQ42SX0VLgxmHuXdUeYHk/fA5bs=
  file:
    - releases/linux-amd64.tar.gz
    - releases/linux-amd64
    - releases/sha256sums.txt
  on:
    repo: KlotzAndrew/callername
    tags: true
