language: go

go:
- 1.13.x

sudo: false

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...

before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  draft: true
  api_key:
    secure: JWBLQWgweRTEu6iWMqHVrgAGcg3DsBM7YeJM72pmXaFuhCd0OsBqr3qwHDXyjOwtRt4Y/ztJMQfkQMrDTyDOND4KmgP2tAXCfFCh+iwggN6t9onjLIf3oY4q5gxof0Hp0+pE0BVIGhBfVtpcXPTJQNkX5A0g05j3Rf12/P2bP/CXEDRTTpfsgFw0VXtxk/DnaV2F272D0v8r2ep0bgSlck8jdFh8bZqudCrTI6JxGX6Ml/vh2YHC+5Yi8teTW5J5trr1jcooQLH/n0Glpj50I3Fet57CZQGy1i6urTQOt2mV4OSxvV2Rw+tWZpzCvlFxbnrGumP1kQNraU16TKHQHIo0sA3TMYTbZ3AGtY6n8zphlrfETYE9PMEBAN6HRaw2iGRn0IUeL1deUGTo5G6Z6QE6d+tbIl0ef086HQ6mW9jnPlIGf/wbAdbi0r1ZbZsxXWL4oucb85h+8hKe58SLVI/oWMkvMQOMqkP6H6qxv+TNLpMWIDWR+W057NBG2AYGE7fu/B0/xE9dusMTD0ugMUWWa5iCLnv4ce1NiP+PWUzNjYwJYDNcDIJ4taK9fak//bGcRXdNhodA/tRFKAG5pZMFP1JXx3PH3iFMMdJQ6x9ZdZIKQzPnwyUgCNNGJ/OzqqMlb4p1QpGfj2s60ghIn1Um6Gp68Ij3nLpqSl/CNVY=
  file:
    - releases/linux-amd64.tar.gz
    - releases/linux-amd64
    - releases/sha512sum.txt
  on:
    repo: KlotzAndrew/callername
    tags: true
